title: In my Lightcone
author: Arun Ravishankar
email: arunravishankar@gmail.com
description: Your awesome blog description
url: http://localhost:4000

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor